boosting:
  params:
    boosting_type : gbdt
    max_depth : 5
    n_estimators : 500
    learning_rate : 0.01
    random_state : 777
    min_child_samples : 3
  features : []
  features_hard_remove : ['year_month_day_hour', 'year_month_day_hour_l1', 'year_month_day_hour_l2', 'year_month_day_hour_l3']

decision_tree:
  params:
    random_state : 777
    max_depth : 40
    min_samples_leaf : 15
  features : []
  features_hard_remove : ['year_month_day_hour', 'year_month_day_hour_l1', 'year_month_day_hour_l2', 'year_month_day_hour_l3']

logistic:


linear:


arima:
  params:
    order : [3, 1, 3]
    freq : h

sarimax:
  params:
    order : [3, 1, 3]
    freq : h
    seasonal_order : [3, 1, 3, 5]
  features : []
  features_hard_remove : []
  